# define LIB_ACTION        "/usr/Game/lib/action"

# define INVENTORY_ACTION  "/usr/Game/data/action/inventory"
# define LOOK_ACTION       "/usr/Game/data/action/look"
# define LOOK_AT_ACTION    "/usr/Game/data/action/look_at"
# define GO_ACTION         "/usr/Game/data/action/go"
# define PICK_UP_ACTION    "/usr/Game/data/action/pick_up"
# define PUT_DOWN_ACTION   "/usr/Game/data/action/put_down"
# define SAY_ACTION        "/usr/Game/data/action/say"
# define SAY_TO_ACTION     "/usr/Game/data/action/say_to"
# define GIVE_ACTION       "/usr/Game/data/action/give"
