# define LIB_ACTION       "/usr/Game/lib/action"

# define DROP_ACTION       "/usr/Game/data/action/drop"
# define GIVE_ACTION       "/usr/Game/data/action/give"
# define GO_ACTION         "/usr/Game/data/action/go"
# define PUT_IN_ACTION     "/usr/Game/data/action/put_in"
# define SAY_ACTION        "/usr/Game/data/action/say"
# define SAY_TO_ACTION     "/usr/Game/data/action/say_to"
# define TAKE_ACTION       "/usr/Game/data/action/take"
# define TAKE_FROM_ACTION  "/usr/Game/data/action/take_from"
# define WEAR_ACTION       "/usr/Game/data/action/wear"
