# define UTIL_ATTRIBUTE             "/usr/Game/lib/util/attribute"
# define LIB_ATTRIBUTE_DISTRIBUTOR  "/usr/Game/lib/attribute_distributor"
# define LIB_ATTRIBUTE_AFFECTOR     "/usr/Game/lib/attribute_affector"

# define STRENGTH_ATTRIBUTE         "strength"
# define SPEED_ATTRIBUTE            "speed"
# define PERCEPTION_ATTRIBUTE       "perception"
# define CHARISMA_ATTRIBUTE         "charisma"

# define ATTACK_ATTRIBUTE           "attack"
# define DEFENSE_ATTRIBUTE          "defense"
# define DAMAGE_ATTRIBUTE           "damage"
# define PROTECTION_ATTRIBUTE       "protection"

# define AGILITY_ATTRIBUTE          "agility"
# define BARGAIN_ATTRIBUTE          "bargain"
# define DEXTERITY_ATTRIBUTE        "dexterity"
# define LEADERSHIP_ATTRIBUTE       "leadership"
# define MAGIC_ATTRIBUTE            "magic"
# define MUSIC_ATTRIBUTE            "music"
# define PRAYER_ATTRIBUTE           "prayer"
# define STEALTH_ATTRIBUTE          "stealth"
