# define COMMANDD          "/usr/Game/sys/commandd"
# define LIB_COMMAND       "/usr/Game/lib/command"

# define GIVE_COMMAND       "/usr/Game/data/command/give"
# define GO_COMMAND         "/usr/Game/data/command/go"
# define INVENTORY_COMMAND  "/usr/Game/data/command/inventory"
# define LOOK_COMMAND       "/usr/Game/data/command/look"
# define LOOK_AT_COMMAND    "/usr/Game/data/command/look_at"
# define PICK_UP_COMMAND    "/usr/Game/data/command/pick_up"
# define PUT_DOWN_COMMAND   "/usr/Game/data/command/put_down"
# define PUT_IN_COMMAND     "/usr/Game/data/command/put_in"
# define SAY_COMMAND        "/usr/Game/data/command/say"
# define SAY_TO_COMMAND     "/usr/Game/data/command/say_to"
# define TAKE_OUT_COMMAND   "/usr/Game/data/command/take_out"
