# define COMMANDD          "/usr/Game/sys/commandd"
# define LIB_COMMAND       "/usr/Game/lib/command"

# define DROP_COMMAND       "/usr/Game/data/command/drop"
# define GIVE_COMMAND       "/usr/Game/data/command/give"
# define GO_COMMAND         "/usr/Game/data/command/go"
# define INVENTORY_COMMAND  "/usr/Game/data/command/inventory"
# define LOOK_COMMAND       "/usr/Game/data/command/look"
# define LOOK_AT_COMMAND    "/usr/Game/data/command/look_at"
# define LOOK_TO_COMMAND    "/usr/Game/data/command/look_to"
# define PUT_IN_COMMAND     "/usr/Game/data/command/put_in"
# define SAY_COMMAND        "/usr/Game/data/command/say"
# define SAY_TO_COMMAND     "/usr/Game/data/command/say_to"
# define TAKE_COMMAND       "/usr/Game/data/command/take"
# define TAKE_FROM_COMMAND  "/usr/Game/data/command/take_from"
# define WEAR_COMMAND       "/usr/Game/data/command/wear"
