# define LIB_GUILD      "/usr/Game/lib/guild"

# define BARD_GUILD     "/usr/Game/guild/bard"
# define KNIGHT_GUILD   "/usr/Game/guild/knight"
# define MONK_GUILD     "/usr/Game/guild/monk"
# define PRIEST_GUILD   "/usr/Game/guild/priest"
# define RANGER_GUILD   "/usr/Game/guild/ranger"
# define THIEF_GUILD    "/usr/Game/guild/thief"
# define WARRIOR_GUILD  "/usr/Game/guild/warrior"
# define WIZARD_GUILD   "/usr/Game/guild/wizard"
